# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='log.proto',
  package='zmq',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tlog.proto\x12\x03zmq\"l\n\nSocketInfo\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.zmq.SocketInfo.Type\x12\n\n\x02id\x18\x02 \x01(\t\".\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03REQ\x10\x01\x12\x07\n\x03SUB\x10\x02\x12\x07\n\x03PUB\x10\x03\" \n\rSocketConnect\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x1d\n\nSocketBind\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x1b\n\x0bSendMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xbf\x01\n\x06\x41\x63tion\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12$\n\x0bsocket_info\x18\x02 \x01(\x0b\x32\x0f.zmq.SocketInfo\x12%\n\x07\x63onnect\x18\x03 \x01(\x0b\x32\x12.zmq.SocketConnectH\x00\x12\x1f\n\x04\x62ind\x18\x04 \x01(\x0b\x32\x0f.zmq.SocketBindH\x00\x12#\n\x07message\x18\x05 \x01(\x0b\x32\x10.zmq.SendMessageH\x00\x42\x0f\n\rdetails_oneofb\x06proto3'
)



_SOCKETINFO_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='zmq.SocketInfo.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQ', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUB', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUB', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=80,
  serialized_end=126,
)
_sym_db.RegisterEnumDescriptor(_SOCKETINFO_TYPE)


_SOCKETINFO = _descriptor.Descriptor(
  name='SocketInfo',
  full_name='zmq.SocketInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='zmq.SocketInfo.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='zmq.SocketInfo.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SOCKETINFO_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=126,
)


_SOCKETCONNECT = _descriptor.Descriptor(
  name='SocketConnect',
  full_name='zmq.SocketConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='zmq.SocketConnect.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=160,
)


_SOCKETBIND = _descriptor.Descriptor(
  name='SocketBind',
  full_name='zmq.SocketBind',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='zmq.SocketBind.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=191,
)


_SENDMESSAGE = _descriptor.Descriptor(
  name='SendMessage',
  full_name='zmq.SendMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='zmq.SendMessage.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=220,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='zmq.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='zmq.Action.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='socket_info', full_name='zmq.Action.socket_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connect', full_name='zmq.Action.connect', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bind', full_name='zmq.Action.bind', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='zmq.Action.message', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='details_oneof', full_name='zmq.Action.details_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=223,
  serialized_end=414,
)

_SOCKETINFO.fields_by_name['type'].enum_type = _SOCKETINFO_TYPE
_SOCKETINFO_TYPE.containing_type = _SOCKETINFO
_ACTION.fields_by_name['socket_info'].message_type = _SOCKETINFO
_ACTION.fields_by_name['connect'].message_type = _SOCKETCONNECT
_ACTION.fields_by_name['bind'].message_type = _SOCKETBIND
_ACTION.fields_by_name['message'].message_type = _SENDMESSAGE
_ACTION.oneofs_by_name['details_oneof'].fields.append(
  _ACTION.fields_by_name['connect'])
_ACTION.fields_by_name['connect'].containing_oneof = _ACTION.oneofs_by_name['details_oneof']
_ACTION.oneofs_by_name['details_oneof'].fields.append(
  _ACTION.fields_by_name['bind'])
_ACTION.fields_by_name['bind'].containing_oneof = _ACTION.oneofs_by_name['details_oneof']
_ACTION.oneofs_by_name['details_oneof'].fields.append(
  _ACTION.fields_by_name['message'])
_ACTION.fields_by_name['message'].containing_oneof = _ACTION.oneofs_by_name['details_oneof']
DESCRIPTOR.message_types_by_name['SocketInfo'] = _SOCKETINFO
DESCRIPTOR.message_types_by_name['SocketConnect'] = _SOCKETCONNECT
DESCRIPTOR.message_types_by_name['SocketBind'] = _SOCKETBIND
DESCRIPTOR.message_types_by_name['SendMessage'] = _SENDMESSAGE
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SocketInfo = _reflection.GeneratedProtocolMessageType('SocketInfo', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETINFO,
  '__module__' : 'log_pb2'
  # @@protoc_insertion_point(class_scope:zmq.SocketInfo)
  })
_sym_db.RegisterMessage(SocketInfo)

SocketConnect = _reflection.GeneratedProtocolMessageType('SocketConnect', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETCONNECT,
  '__module__' : 'log_pb2'
  # @@protoc_insertion_point(class_scope:zmq.SocketConnect)
  })
_sym_db.RegisterMessage(SocketConnect)

SocketBind = _reflection.GeneratedProtocolMessageType('SocketBind', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETBIND,
  '__module__' : 'log_pb2'
  # @@protoc_insertion_point(class_scope:zmq.SocketBind)
  })
_sym_db.RegisterMessage(SocketBind)

SendMessage = _reflection.GeneratedProtocolMessageType('SendMessage', (_message.Message,), {
  'DESCRIPTOR' : _SENDMESSAGE,
  '__module__' : 'log_pb2'
  # @@protoc_insertion_point(class_scope:zmq.SendMessage)
  })
_sym_db.RegisterMessage(SendMessage)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'log_pb2'
  # @@protoc_insertion_point(class_scope:zmq.Action)
  })
_sym_db.RegisterMessage(Action)


# @@protoc_insertion_point(module_scope)
